### ISSUE TITLE
submodule not included in GitHub download and plain repository clone

### ISSUE THREAD

**Issue by SYoung82** [sirl1on/plugin.audio.pocketcasts#1]
When trying to run pocketcasts add-on for kodi I get an error which will not allow add-on to start.  The relevant log information pasted below.  Any help would be appreciated.

01:43:11  35.130489 T:1384117152  NOTICE: 01:43:05  29.102787 T:1540772768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named pocketcasts
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.pocketcasts-master/addon.py", line 12, in <module>
                                                import pocketcasts
                                            ImportError: No module named pocketcasts
                                            -->End of Python script error report<--
01:43:05  29.174999 T:1963655744   ERROR: GetDirectory - Error getting plugin://plugin.audio.pocketcasts/
01:43:05  29.175327 T:1963655744   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.pocketcasts/) failedEMBY.database -> opened: /storage/.kodi/userdata/Database/emby.db - 1401833472

**Comment by koalajoe23** [comment]
Hello!

First: I relly appreciate using my project. Is not really complete, stable or tested and I was and am doing it just as a side project.

Your git checkout or github download doesn't contain the resources/lib/python-pocketcasts folder, which is a git-submodule and not downloaded automatically via Github web interface or standard git clone. As a temporary fix:

Download the plugin via git on the command line:
`git clone --recursive https://github.com/sirl1on/plugin.audio.pocketcasts.git`

and creating a zip file of the downloaded contents.

Thanks again and don't hesitate to report any bugs or inconsistencies :)

**Comment by SYoung82** [comment]
Fix worked like a charm.  Excellent work!  Wish I knew python better I'd try to help you with improvements.  Keep up the good work.

**Comment by koalajoe23** [comment]
Thank you! The add-on should be also downloadable via GitHub now!
